### ISSUE TITLE
import plotly fail while plotly is already installed 

### ISSUE THREAD

**Issue by AndiIsBroke** [ANTsX/ANTsPy#126]
hey guys I was tryna simply import ants and it suggested:
`Cant import Plotly. Install it `pip install plotly` if you want to use ants.render_surface_function`
so I just manually installed plotly4.5.2 before trying again but still:
`>>> import plotly
>>> import ants
/gs/home/hanad/.conda/envs/testenv/lib/python3.6/site-packages/ants/viz/render_surface_function.py:16: UserWarning:

Cant import Plotly. Install it `pip install plotly` if you want to use ants.render_surface_function
`
pls help! so much thanks.
Andi 29Feb2020

**Comment by stnava** [comment]
this should be fixed now.  let me know if it works for you.   these visualization tools are not much tested.

**Comment by AndiIsBroke** [comment]
> this should be fixed now. let me know if it works for you. these visualization tools are not much tested.

no luck with it. still the same error.

**Comment by stnava** [comment]
you have to reinstall from source.

brian

**Comment by stnava** [comment]
closing due to inactivity and b/c it looks resolved at least with local testing.

**Comment by zheng-broad** [comment]
I am still getting this issue, I installed plotly 4.12.0 and am getting the exact same error trying to import ants.
